name: Test Action
description: Test Action
inputs:
  name:
    description: 'Name of the person to greet'
    required: true
    default: 'World'
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: mstefaniak/gh_action
        ref: main
        path: test
    
    - name: Debug
      shell: bash
      run: ls -la
    - name: Test
      shell: bash
      run: script.sh