name: Test Action
description: Test Action
inputs:
  name:
    description: 'Name of the person to greet'
    required: true
    default: 'World'
runs:
  using: composite
  steps:
    - name: Test
      shell: bash
      run: script.sh